# Generated by Django 4.2.5 on 2023-09-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
