# Generated by Django 4.2.5 on 2023-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
